import type { Metadata } from "next";
// Fonts come from the `geist` npm package rather than next/font/google: Google
// Fonts is fetched at build time, which breaks the offline build the clinic
// promises (see specs/tech-stack.md, "Parity rules").
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
